DROP DATABASE IF EXISTS Papyrus2;
CREATE DATABASE Papyrus2;
USE Papyrus2;
DROP TABLE IF EXISTS produit;
CREATE TABLE produit(
    CODART CHAR(4) NOT NULL,
    LIBART VARCHAR(30) NOT NULL,
    STKALE INT(10) NOT NULL,
    STKPHY INT(10) NOT NULL,
    QTEANN INT(10) NOT NULL,
    UNIMES CHAR(5) NOT NULL,
    PRIMARY KEY (CODART)
);
DROP TABLE IF EXISTS fournis;
CREATE TABLE fournis(
    NUMFOU VARCHAR(25) NOT NULL,
    NOMFOU VARCHAR(25) NOT NULL,
    RUEFOU VARCHAR(25) NOT NULL,
    POSFOU CHAR(5) NOT NULL,
    VILFOU VARCHAR(30) NOT NULL,
    CONFOU VARCHAR(15) NOT NULL,
    SATISF TINYINT(2),
    -- TINYINT(2)=0 à 10 TINYINT(3)=0 à 100 ETC...
    PRIMARY KEY (NUMFOU)
);
DROP TABLE IF EXISTS entcom;
CREATE TABLE entcom(
    NUMCOM INT(10) AUTO_INCREMENT NOT NULL,
    OBSCOM VARCHAR(50),
    DATCOM TIMESTAMP NOT NULL,
    NUMFOU VARCHAR(25),
    PRIMARY KEY (NUMCOM),
    FOREIGN KEY (NUMFOU) REFERENCES fournis(NUMFOU)
);
DROP TABLE IF EXISTS ligcom;
CREATE TABLE ligcom(
    NUMLIG TINYINT(3) NOT NULL,
    QTECDE INT(10) NOT NULL,
    PRIUNI VARCHAR(50) NOT NULL,
    QTELIV INT(10),
    DERLIV DATE NOT NULL,
    NUMCOM INT(10) NOT NULL,
    CODART CHAR(4) NOT NULL,
    PRIMARY KEY (NUMLIG, NUMCOM),
    FOREIGN KEY (NUMCOM) REFERENCES entcom(NUMCOM),
    FOREIGN KEY (CODART) REFERENCES produit(CODART)
);
DROP TABLE IF EXISTS vente;
CREATE TABLE vente(
    NUMFOU VARCHAR(25),
    CODART CHAR(4),
    DELLIV SMALLINT(5),
    QTE1 INT(10),
    PRIX1 VARCHAR(50),
    QTE2 INT(10),
    PRIX2 VARCHAR(50),
    QTE3 INT(10),
    PRIX3 VARCHAR(50),
    PRIMARY KEY (NUMFOU, CODART),
    FOREIGN KEY (NUMFOU) REFERENCES fournis(NUMFOU),
    FOREIGN KEY (CODART) REFERENCES produit(CODART)
);